/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData home = IconData(0xe318, fontFamily: 'MaterialIcons');
  static const IconData note_alt = IconData(0xe44b, fontFamily: 'MaterialIcons');
  static const IconData chat = IconData(0xe153, fontFamily: 'MaterialIcons');
  static const IconData account_box_rounded = IconData(0xf521, fontFamily: 'MaterialIcons');
  static const IconData privacy = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  
}
